services:
  - type: web
    name: learnsmart-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
